"""initial_schema

Revision ID: da2227216072
Revises: 
Create Date: 2026-08-12 10:08:53.052863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2227216072'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ait_requirement_id', 'ai_tasks', ['requirement_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_branch_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_empty', sa.Boolean(), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('test_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_case_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cb_generated_case_id', 'case_bindings', ['generated_case_id'], unique=False)
    op.create_table('case_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('checks', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cr_requirement_id', 'case_reviews', ['requirement_id'], unique=False)
    op.create_table('coverage_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('requirement_coverage', sa.Integer(), nullable=False),
    sa.Column('story_coverage', sa.Integer(), nullable=False),
    sa.Column('test_point_coverage', sa.Integer(), nullable=False),
    sa.Column('scenario_coverage', sa.Integer(), nullable=False),
    sa.Column('case_coverage', sa.Integer(), nullable=False),
    sa.Column('automation_coverage', sa.Integer(), nullable=False),
    sa.Column('risk_coverage', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cov_requirement_id', 'coverage_snapshots', ['requirement_id'], unique=False)
    op.create_table('defect_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.String(length=64), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('case_uid', sa.String(length=256), nullable=False),
    sa.Column('case_name', sa.String(length=512), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('bug_type', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.String(length=32), nullable=False),
    sa.Column('resolved_version', sa.Integer(), nullable=False),
    sa.Column('duplicate_defect_id', sa.Integer(), nullable=False),
    sa.Column('resolved_date', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=16), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('case_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('method_name', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('trace', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('test_type', sa.String(length=16), nullable=False),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ec_execution_id', 'execution_cases', ['execution_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('running_count', sa.Integer(), nullable=False),
    sa.Column('waiting_count', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('sequential', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_table('generated_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gc_requirement_id', 'generated_cases', ['requirement_id'], unique=False)
    op.create_index('idx_gc_story_id', 'generated_cases', ['story_id'], unique=False)
    op.create_table('information_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('gap_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ig_requirement_id', 'information_gaps', ['requirement_id'], unique=False)
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('api_base', sa.String(length=512), nullable=False),
    sa.Column('text_model', sa.String(length=128), nullable=False),
    sa.Column('vision_model', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('case_uid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('server_path', sa.String(length=1024), nullable=False),
    sa.Column('test_path', sa.String(length=512), nullable=False),
    sa.Column('report_output', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('new_case_count', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('module_groups', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_execution_id'), 'reports', ['execution_id'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('requirement_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('elements', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ra_requirement_id', 'requirement_analyses', ['requirement_id'], unique=False)
    op.create_table('requirement_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rqas_asset_type', 'requirement_assets', ['requirement_id', 'asset_type'], unique=False)
    op.create_index('idx_rqas_parent_id', 'requirement_assets', ['parent_id'], unique=False)
    op.create_index('idx_rqas_requirement_id', 'requirement_assets', ['requirement_id'], unique=False)
    op.create_index('idx_rqas_story_id', 'requirement_assets', ['story_id'], unique=False)
    op.create_table('requirement_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rr_requirement_id', 'requirement_reviews', ['requirement_id'], unique=False)
    op.create_table('requirement_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('link', sa.String(length=1024), nullable=False),
    sa.Column('text_content', sa.Text(length=16777216), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('extracted', sa.Boolean(), nullable=False),
    sa.Column('extract_error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rs_requirement_id', 'requirement_sources', ['requirement_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_meta', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_req_project_branch', 'requirements', ['project_id', 'branch_id'], unique=False)
    op.create_table('review_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('dimension_scores', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('information_gaps', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rva_artifact', 'review_audits', ['artifact_type', 'artifact_id'], unique=False)
    op.create_table('scenario_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sr_requirement_id', 'scenario_reviews', ['requirement_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=False),
    sa.Column('dimension_scores', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('dependencies', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_story_requirement_id', 'stories', ['requirement_id'], unique=False)
    op.create_table('task_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case_definitions',
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('method_name', sa.String(length=256), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=False),
    sa.Column('module', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=1024), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('test_type', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'project_id', 'branch_id')
    )
    op.create_table('test_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tg_requirement_id', 'test_gaps', ['requirement_id'], unique=False)
    op.create_table('test_point_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('dimension_scores', sa.Text(), nullable=False),
    sa.Column('coverage', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tpr_requirement_id', 'test_point_reviews', ['requirement_id'], unique=False)
    op.create_table('test_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tp_parent_id', 'test_points', ['parent_id'], unique=False)
    op.create_index('idx_tp_requirement_id', 'test_points', ['requirement_id'], unique=False)
    op.create_index('idx_tp_story_id', 'test_points', ['story_id'], unique=False)
    op.create_table('test_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('test_point_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('coverage_dim', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ts_requirement_id', 'test_scenarios', ['requirement_id'], unique=False)
    op.create_index('idx_ts_test_point_id', 'test_scenarios', ['test_point_id'], unique=False)
    op.create_table('test_strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('automation_ratio', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tstr_requirement_id', 'test_strategies', ['requirement_id'], unique=False)
    op.create_table('user_active_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_lark_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('lark_open_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_lark_bindings')
    op.drop_table('user_active_projects')
    op.drop_index('idx_tstr_requirement_id', table_name='test_strategies')
    op.drop_table('test_strategies')
    op.drop_index('idx_ts_test_point_id', table_name='test_scenarios')
    op.drop_index('idx_ts_requirement_id', table_name='test_scenarios')
    op.drop_table('test_scenarios')
    op.drop_index('idx_tp_story_id', table_name='test_points')
    op.drop_index('idx_tp_requirement_id', table_name='test_points')
    op.drop_index('idx_tp_parent_id', table_name='test_points')
    op.drop_table('test_points')
    op.drop_index('idx_tpr_requirement_id', table_name='test_point_reviews')
    op.drop_table('test_point_reviews')
    op.drop_index('idx_tg_requirement_id', table_name='test_gaps')
    op.drop_table('test_gaps')
    op.drop_table('test_case_definitions')
    op.drop_table('tasks')
    op.drop_table('task_cases')
    op.drop_index('idx_story_requirement_id', table_name='stories')
    op.drop_table('stories')
    op.drop_index('idx_sr_requirement_id', table_name='scenario_reviews')
    op.drop_table('scenario_reviews')
    op.drop_index('idx_rva_artifact', table_name='review_audits')
    op.drop_table('review_audits')
    op.drop_index('idx_req_project_branch', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('idx_rs_requirement_id', table_name='requirement_sources')
    op.drop_table('requirement_sources')
    op.drop_index('idx_rr_requirement_id', table_name='requirement_reviews')
    op.drop_table('requirement_reviews')
    op.drop_index('idx_rqas_story_id', table_name='requirement_assets')
    op.drop_index('idx_rqas_requirement_id', table_name='requirement_assets')
    op.drop_index('idx_rqas_parent_id', table_name='requirement_assets')
    op.drop_index('idx_rqas_asset_type', table_name='requirement_assets')
    op.drop_table('requirement_assets')
    op.drop_index('idx_ra_requirement_id', table_name='requirement_analyses')
    op.drop_table('requirement_analyses')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_execution_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('projects')
    op.drop_table('project_notes')
    op.drop_table('project_members')
    op.drop_table('project_cases')
    op.drop_table('llm_settings')
    op.drop_index('idx_ig_requirement_id', table_name='information_gaps')
    op.drop_table('information_gaps')
    op.drop_index('idx_gc_story_id', table_name='generated_cases')
    op.drop_index('idx_gc_requirement_id', table_name='generated_cases')
    op.drop_table('generated_cases')
    op.drop_table('executions')
    op.drop_index('idx_ec_execution_id', table_name='execution_cases')
    op.drop_table('execution_cases')
    op.drop_table('defects')
    op.drop_table('defect_modules')
    op.drop_table('defect_logs')
    op.drop_table('defect_comments')
    op.drop_table('defect_attachments')
    op.drop_index('idx_cov_requirement_id', table_name='coverage_snapshots')
    op.drop_table('coverage_snapshots')
    op.drop_index('idx_cr_requirement_id', table_name='case_reviews')
    op.drop_table('case_reviews')
    op.drop_index('idx_cb_generated_case_id', table_name='case_bindings')
    op.drop_table('case_bindings')
    op.drop_table('branches')
    op.drop_index('idx_ait_requirement_id', table_name='ai_tasks')
    op.drop_table('ai_tasks')
    # ### end Alembic commands ###
